// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Utils$ReactHooksTemplate = require("./Utils.bs.js");
var Styles1$ReactHooksTemplate = require("./Styles1.bs.js");
var ItemDisplay$ReactHooksTemplate = require("./ItemDisplay.bs.js");
var ContextProvider$ReactHooksTemplate = require("./ContextProvider.bs.js");

function Block(Props) {
  var items = Props.items;
  var goToBlock = Props.goToBlock;
  var goToDetail = Props.goToDetail;
  var theme = React.useContext(ContextProvider$ReactHooksTemplate.themeContext);
  return React.createElement("div", {
              className: Styles1$ReactHooksTemplate.container(theme)
            }, React.createElement("div", {
                  className: Styles1$ReactHooksTemplate.title(theme)
                }, "Block"), React.createElement(ItemDisplay$ReactHooksTemplate.make, {
                  entity: "block",
                  items: items,
                  changeLevel: goToBlock,
                  goToDetail: goToDetail
                }), React.createElement("div", {
                  className: Styles1$ReactHooksTemplate.linkBtn(theme)
                }, "All Operations >>"));
}

var make = Block;

exports.make = make;
/* react Not a pure module */
