// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var configs = /* array */[
  /* record */[
    /* url */"https://conseil-prod.cryptonomic-infra.tech:443",
    /* apiKey */"galleon",
    /* platform */"tezos",
    /* network */"mainnet",
    /* displayName */"Tezos Mainnet"
  ],
  /* record */[
    /* url */"https://conseil-dev.cryptonomic-infra.tech:443",
    /* apiKey */"hooman",
    /* platform */"tezos",
    /* network */"alphanet",
    /* displayName */"Tezos Alphanet"
  ]
];

exports.configs = configs;
/* No side effect */
