// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var themeContext = React.createContext(0);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = themeContext.Provider;

exports.themeContext = themeContext;
exports.makeProps = makeProps;
exports.make = make;
/* themeContext Not a pure module */
