// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Themes$ReactHooksTemplate = require("./themes.bs.js");
var Configs$ReactHooksTemplate = require("./configs.bs.js");
var ContextProvider$ReactHooksTemplate = require("./ContextProvider.bs.js");

var container = Css.style(/* :: */[
      Css.position(Css.fixed),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.justifyContent(Css.center),
            /* :: */[
              Css.backgroundColor(Css.rgba(0, 0, 0, 0.3)),
              /* :: */[
                Css.top(Css.px(0)),
                /* :: */[
                  Css.left(Css.px(0)),
                  /* :: */[
                    Css.width(Css.pct(100)),
                    /* :: */[
                      Css.height(Css.vh(100)),
                      /* :: */[
                        Css.zIndex(50),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function mainContainer(index) {
  return Css.style(/* :: */[
              Css.width(Css.px(400)),
              /* :: */[
                Css.height(Css.px(285)),
                /* :: */[
                  Css.padding(Css.px(15)),
                  /* :: */[
                    Css.backgroundColor(Css.hex("c22c2c")),
                    /* :: */[
                      Css.boxShadows(/* :: */[
                            Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.2)),
                            /* :: */[
                              Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.14)),
                              /* :: */[
                                Css.boxShadow(Css.px(20), Css.px(20), Css.px(0), Css.px(0), undefined, Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                /* [] */0
                              ]
                            ]
                          ]),
                      /* :: */[
                        Css.textAlign(Css.center),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var borderContainer = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.height(Css.pct(100)),
        /* :: */[
          Css.padding(Css.px(4)),
          /* :: */[
            Css.border(Css.px(2), Css.solid, Css.white),
            /* [] */0
          ]
        ]
      ]
    ]);

var contentContainer = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.height(Css.pct(100)),
        /* :: */[
          Css.border(Css.px(2), Css.solid, Css.white),
          /* [] */0
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.position(Css.relative),
      /* :: */[
        Css.fontSize(Css.px(20)),
        /* :: */[
          Css.color(Css.white),
          /* :: */[
            Css.letterSpacing(Css.px(2)),
            /* :: */[
              Css.display(Css.inlineBlock),
              /* :: */[
                Css.padding4(Css.px(0), Css.px(15), Css.px(0), Css.px(15)),
                /* :: */[
                  Css.top(Css.px(-13)),
                  /* :: */[
                    Css.backgroundColor(Css.hex("c22c2c")),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function okBtn(index) {
  return Css.style(/* :: */[
              Css.fontSize(Css.px(20)),
              /* :: */[
                Css.padding4(Css.px(7), Css.px(15), Css.px(7), Css.px(15)),
                /* :: */[
                  Css.minWidth(Css.px(100)),
                  /* :: */[
                    Css.backgroundColor(Css.hex("EEFF00")),
                    /* :: */[
                      Css.boxShadows(/* :: */[
                            Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.2)),
                            /* :: */[
                              Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.14)),
                              /* :: */[
                                Css.boxShadow(Css.px(12), Css.px(10), Css.px(0), Css.px(0), undefined, Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                /* [] */0
                              ]
                            ]
                          ]),
                      /* :: */[
                        Css.textAlign(Css.center),
                        /* :: */[
                          Css.letterSpacing(Css.px(1)),
                          /* :: */[
                            Css.fontFamily("'Perfect DOS VGA 437 Win', sans-serif"),
                            /* :: */[
                              Css.outline(Css.px(0), Css.none, Css.transparent),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var selectContainer = Css.style(/* :: */[
      Css.padding4(Css.px(30), Css.px(48), Css.px(10), Css.px(48)),
      /* [] */0
    ]);

var rowcontainer = Css.style(/* :: */[
      Css.fontSize(Css.px(20)),
      /* :: */[
        Css.marginBottom(Css.px(35)),
        /* :: */[
          Css.display(Css.flexBox),
          /* :: */[
            Css.alignItems(Css.center),
            /* [] */0
          ]
        ]
      ]
    ]);

function checkBtn(index) {
  return Css.style(/* :: */[
              Css.marginRight(Css.px(40)),
              /* :: */[
                Css.width(Css.px(20)),
                /* :: */[
                  Css.height(Css.px(20)),
                  /* :: */[
                    Css.fontFamily("'Perfect DOS VGA 437 Win', sans-serif"),
                    /* :: */[
                      Css.boxShadow(Css.px(3), Css.px(3), Css.px(0), Css.px(0), undefined, Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                      /* :: */[
                        Css.border(Css.px(0), Css.none, Css.transparent),
                        /* :: */[
                          Css.outline(Css.px(0), Css.none, Css.transparent),
                          /* :: */[
                            Css.fontSize(Css.px(18)),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[
  /* container */container,
  /* mainContainer */mainContainer,
  /* borderContainer */borderContainer,
  /* contentContainer */contentContainer,
  /* title */title,
  /* okBtn */okBtn,
  /* selectContainer */selectContainer,
  /* rowcontainer */rowcontainer,
  /* checkBtn */checkBtn
];

function NetworkSelector(Props) {
  var selectedIndex = Props.selectedIndex;
  var onChange = Props.onChange;
  var onCancel = Props.onCancel;
  var theme = React.useContext(ContextProvider$ReactHooksTemplate.themeContext);
  var match = React.useState((function () {
          return selectedIndex;
        }));
  var setSelected = match[1];
  var selected = match[0];
  var confirm = function (_event) {
    Curry._1(onChange, selected);
    _event.stopPropagation();
    return /* () */0;
  };
  var stop = function (_event) {
    _event.stopPropagation();
    return /* () */0;
  };
  return React.createElement("div", {
              className: container,
              onClick: (function (param) {
                  return Curry._1(onCancel, /* () */0);
                })
            }, React.createElement("div", {
                  className: mainContainer(theme),
                  onClick: stop
                }, React.createElement("div", {
                      className: borderContainer
                    }, React.createElement("div", {
                          className: contentContainer
                        }, React.createElement("div", {
                              className: title
                            }, "Select a Network"), React.createElement("div", {
                              className: selectContainer
                            }, $$Array.mapi((function (index, config) {
                                    var match = selected === index;
                                    return React.createElement("div", {
                                                key: config[/* network */3],
                                                className: rowcontainer
                                              }, React.createElement("button", {
                                                    className: checkBtn(theme),
                                                    onClick: (function (_ev) {
                                                        var _event = _ev;
                                                        var index$1 = index;
                                                        Curry._1(setSelected, (function (param) {
                                                                return index$1;
                                                              }));
                                                        _event.stopPropagation();
                                                        return /* () */0;
                                                      })
                                                  }, match ? "x" : ""), config[/* displayName */4]);
                                  }), Configs$ReactHooksTemplate.configs)), React.createElement("button", {
                              className: okBtn(theme),
                              onClick: confirm
                            }, "Ok")))));
}

var make = NetworkSelector;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
