// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Themes$ReactHooksTemplate = require("./themes.bs.js");

function container(index) {
  return Css.style(/* :: */[
              Css.width(Css.pct(100)),
              /* :: */[
                Css.paddingLeft(Css.px(11)),
                /* :: */[
                  Css.position(Css.relative),
                  /* :: */[
                    Css.before(/* :: */[
                          Css.contentRule(""),
                          /* :: */[
                            Css.position(Css.absolute),
                            /* :: */[
                              Css.width(Css.px(2)),
                              /* :: */[
                                Css.height(Css.Calc[/* - */0](Css.pct(100), Css.px(29))),
                                /* :: */[
                                  Css.backgroundColor(Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                  /* :: */[
                                    Css.left(Css.px(0)),
                                    /* :: */[
                                      Css.top(Css.px(16)),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function titleLinkCss(index) {
  return /* :: */[
          Css.position(Css.relative),
          /* :: */[
            Css.height(Css.px(31)),
            /* :: */[
              Css.padding4(Css.px(6), Css.px(9), Css.px(6), Css.px(9)),
              /* :: */[
                Css.fontSize(Css.px(20)),
                /* :: */[
                  Css.color(Css.black),
                  /* :: */[
                    Css.backgroundColor(Css.white),
                    /* :: */[
                      Css.boxShadows(/* :: */[
                            Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.2)),
                            /* :: */[
                              Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.14)),
                              /* :: */[
                                Css.boxShadow(Css.px(7), Css.px(7), Css.px(0), Css.px(0), undefined, Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                /* [] */0
                              ]
                            ]
                          ]),
                      /* :: */[
                        Css.before(/* :: */[
                              Css.contentRule(""),
                              /* :: */[
                                Css.position(Css.absolute),
                                /* :: */[
                                  Css.width(Css.px(8)),
                                  /* :: */[
                                    Css.height(Css.px(2)),
                                    /* :: */[
                                      Css.backgroundColor(Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                      /* :: */[
                                        Css.left(Css.px(-9)),
                                        /* :: */[
                                          Css.top(Css.px(16)),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ];
}

function title(index) {
  return Css.style(/* :: */[
              Css.textTransform(Css.capitalize),
              /* :: */[
                Css.width(Css.px(215)),
                titleLinkCss(index)
              ]
            ]);
}

function linkBtn(index) {
  return Css.style(/* :: */[
              Css.width(Css.px(215)),
              /* :: */[
                Css.cursor(/* pointer */-786317123),
                /* :: */[
                  Css.marginTop(Css.px(10)),
                  titleLinkCss(index)
                ]
              ]
            ]);
}

function accountBtn(index) {
  return Css.style(/* :: */[
              Css.width(Css.px(485)),
              /* :: */[
                Css.cursor(/* pointer */-786317123),
                /* :: */[
                  Css.marginTop(Css.px(15)),
                  titleLinkCss(index)
                ]
              ]
            ]);
}

var titleContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.alignItems(Css.center),
        /* [] */0
      ]
    ]);

var titleBtnContainer = Css.style(/* :: */[
      Css.marginLeft(Css.px(30)),
      /* [] */0
    ]);

function transactionBtn(index, disabled) {
  return Css.style(/* :: */[
              Css.width(Css.px(31)),
              /* :: */[
                Css.height(Css.px(31)),
                /* :: */[
                  Css.fontSize(Css.px(20)),
                  /* :: */[
                    Css.border(Css.px(0), Css.none, Css.transparent),
                    /* :: */[
                      Css.outline(Css.px(0), Css.none, Css.transparent),
                      /* :: */[
                        Css.color(Css.black),
                        /* :: */[
                          Css.backgroundColor(Css.hex("EEFF00")),
                          /* :: */[
                            Css.boxShadows(/* :: */[
                                  Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.2)),
                                  /* :: */[
                                    Css.boxShadow(Css.px(0), Css.px(4), Css.px(12), Css.px(0), undefined, Css.rgba(0, 0, 0, 0.14)),
                                    /* :: */[
                                      Css.boxShadow(Css.px(7), Css.px(7), Css.px(0), Css.px(0), undefined, Css.hex(Caml_array.caml_array_get(Themes$ReactHooksTemplate.themes, index)[/* fieldBgColor */1])),
                                      /* [] */0
                                    ]
                                  ]
                                ]),
                            /* :: */[
                              Css.marginRight(Css.px(7)),
                              /* :: */[
                                Css.opacity(disabled ? 0.7 : 1),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

exports.container = container;
exports.titleLinkCss = titleLinkCss;
exports.title = title;
exports.linkBtn = linkBtn;
exports.accountBtn = accountBtn;
exports.titleContainer = titleContainer;
exports.titleBtnContainer = titleBtnContainer;
exports.transactionBtn = transactionBtn;
/* titleContainer Not a pure module */
