// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var themes = /* array */[
  /* record */[
    /* mainBgColor */"2B2BFF",
    /* fieldBgColor */"000000",
    /* searchBgColor */"ffffff",
    /* fieldColor */"ffffff",
    /* valueColor */"eeff00"
  ],
  /* record */[
    /* mainBgColor */"000000",
    /* fieldBgColor */"00ff66",
    /* searchBgColor */"00ff66",
    /* fieldColor */"000000",
    /* valueColor */"00ff66"
  ]
];

exports.themes = themes;
/* No side effect */
