// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var initState_007 = /* block */{ };

var initState_008 = /* account */{ };

var initState_009 = /* operation : array */[];

var initState = /* record */[
  /* entity */"",
  /* id */"",
  /* isLoading */false,
  /* selectedConfig */0,
  /* isOpenNetworkSelector */false,
  /* isError */false,
  /* error */"",
  initState_007,
  initState_008,
  initState_009
];

exports.initState = initState;
/* No side effect */
